import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FreelanceOnboardingService } from '../../../../core/freelance/services/freelance-onboarding.service';

@Component({ selector:'app-identity-password-reset', standalone:true, imports:[CommonModule,ReactiveFormsModule,RouterModule], changeDetection:ChangeDetectionStrategy.OnPush,
template:`<section class="reset"><h2>{{ token() ? 'تعيين كلمة مرور جديدة' : 'استعادة كلمة المرور' }}</h2>@if (done()) { <p class="success">{{ done() }}</p><a routerLink="/identity/login">العودة لتسجيل الدخول</a> } @else if (token()) { <p>اختر كلمة مرور جديدة قوية. سيُسجّل الخروج من كل الجلسات القديمة.</p><form [formGroup]="passwordForm" (ngSubmit)="reset()"><label>كلمة المرور الجديدة<input type="password" class="form-input" formControlName="password" autocomplete="new-password" dir="ltr"></label><label>تأكيد كلمة المرور<input type="password" class="form-input" formControlName="confirmPassword" autocomplete="new-password" dir="ltr"></label><button class="btn btn-primary" [disabled]="loading()||passwordForm.invalid">{{loading()?'جارٍ الحفظ...':'حفظ كلمة المرور'}}</button></form> } @else { <p>أدخل بريدك الإلكتروني وسنرسل رابطًا آمنًا إذا كان الحساب مؤهلاً.</p><form [formGroup]="emailForm" (ngSubmit)="request()"><label>البريد الإلكتروني<input type="email" class="form-input" formControlName="email" autocomplete="email" dir="ltr"></label><button class="btn btn-primary" [disabled]="loading()||emailForm.invalid">{{loading()?'جارٍ الإرسال...':'إرسال رابط الاستعادة'}}</button></form> } @if(error()){<p class="error">{{error()}}</p>}</section>`,
styles:[`.reset h2{margin:0 0 .6rem;color:var(--text-primary)}.reset p{color:var(--text-secondary);line-height:1.7}.reset form{display:grid;gap:.8rem;margin-top:1rem}.reset label{display:grid;gap:.35rem;font-weight:600;color:var(--text-primary)}.form-input{min-height:44px;padding:.65rem .75rem;border:1px solid var(--border-color);border-radius:8px;background:var(--bg-primary);color:var(--text-primary)}.btn{min-height:46px}.error{color:#b91c1c}.success{padding:.8rem;border-radius:.6rem;background:#f0fdf4;color:#166534!important}`] })
export class IdentityPasswordResetComponent { private readonly route=inject(ActivatedRoute); private readonly fb=inject(FormBuilder); private readonly onboarding=inject(FreelanceOnboardingService); readonly token=signal<string|null>(null); readonly loading=signal(false); readonly error=signal(''); readonly done=signal(''); readonly emailForm=this.fb.nonNullable.group({email:['',[Validators.required,Validators.email]]}); readonly passwordForm=this.fb.nonNullable.group({password:['',[Validators.required,Validators.minLength(8)]],confirmPassword:['',Validators.required]}); constructor(){this.route.fragment.subscribe(fragment=>this.token.set(new URLSearchParams(fragment||'').get('token')));} request():void{if(this.emailForm.invalid){this.emailForm.markAllAsTouched();return;}this.loading.set(true);this.error.set('');this.onboarding.requestIdentityPasswordReset(this.emailForm.getRawValue().email).subscribe({next:()=>{this.loading.set(false);this.done.set('إذا كان الحساب موجودًا ومؤهلاً، ستصلك رسالة برابط الاستعادة.');},error:err=>{this.loading.set(false);this.error.set(err?.translatedMessage||err?.error?.message||'تعذر إرسال الطلب.');}});} reset():void{if(this.passwordForm.invalid){this.passwordForm.markAllAsTouched();return;}const data=this.passwordForm.getRawValue();if(data.password!==data.confirmPassword){this.error.set('كلمتا المرور غير متطابقتين.');return;}const token=this.token();if(!token)return;this.loading.set(true);this.error.set('');this.onboarding.resetIdentityPassword(token,data.password).subscribe({next:()=>{this.loading.set(false);this.done.set('تم تغيير كلمة المرور وإلغاء الجلسات القديمة.');},error:err=>{this.loading.set(false);this.error.set(err?.translatedMessage||err?.error?.message||'الرابط غير صالح أو منتهي الصلاحية.');}});} }
