import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { FreelanceOnboardingService } from '../../../../core/freelance/services/freelance-onboarding.service';

@Component({ selector: 'app-identity-password-reset', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterModule], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section class="reset" dir="rtl"><p class="eyebrow">استعادة آمنة</p><h2>{{ token() ? 'تعيين كلمة مرور جديدة' : 'استعادة كلمة المرور' }}</h2>@if (done()) { <p class="success">{{ done() }}</p><a routerLink="/identity/login">العودة لتسجيل الدخول</a> } @else if (token()) { <p>استخدم رابط البريد لتعيين كلمة مرور جديدة، وستُلغى الجلسات القديمة.</p><form [formGroup]="passwordForm" (ngSubmit)="reset()"><ng-container [ngTemplateOutlet]="passwordFields"></ng-container><button [disabled]="loading() || passwordForm.invalid">{{ loading() ? 'جارٍ الحفظ...' : 'حفظ كلمة المرور' }}</button></form> } @else { <p>أدخل بريدك وسنرسل رابطًا آمنًا إذا كان الحساب مؤهلًا.</p><form [formGroup]="emailForm" (ngSubmit)="request()"><label>البريد الإلكتروني<input type="email" formControlName="email" autocomplete="email" dir="ltr"></label><button [disabled]="loading() || emailForm.invalid">{{ loading() ? 'جارٍ الإرسال...' : 'إرسال رابط الاستعادة' }}</button></form> } @if (error()) { <p class="error">{{ error() }}</p> }<ng-template #passwordFields><label>كلمة المرور الجديدة<input type="password" formControlName="password" autocomplete="new-password" dir="ltr"></label><label>تأكيد كلمة المرور<input type="password" formControlName="confirmPassword" autocomplete="new-password" dir="ltr"></label></ng-template></section>`,
  styles: [`.reset h2{margin:.25rem 0;color:var(--text-primary)}.eyebrow{color:#2563eb;font-size:.75rem;font-weight:900}.reset>p{color:var(--text-secondary);line-height:1.7}form{display:grid;gap:.7rem;margin-top:1rem}label{display:grid;gap:.35rem;font-weight:700}input{min-height:46px;padding:.65rem;border:1px solid var(--border-color);border-radius:9px;background:var(--bg-primary);color:var(--text-primary);font:inherit}form>button{min-height:46px;border:0;border-radius:9px;background:#2563eb;color:#fff;font:inherit;font-weight:800}.error{color:#b91c1c}.success{padding:.8rem;border-radius:.6rem;background:#f0fdf4;color:#166534}`],
})
export class IdentityPasswordResetComponent {
  private readonly route = inject(ActivatedRoute); private readonly fb = inject(FormBuilder); private readonly onboarding = inject(FreelanceOnboardingService);
  readonly token = signal<string|null>(null); readonly loading = signal(false); readonly error = signal(''); readonly done = signal(''); readonly emailForm = this.fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]] }); readonly passwordForm = this.fb.nonNullable.group({ password: ['', [Validators.required, Validators.minLength(8)]], confirmPassword: ['', Validators.required] });
  constructor() { this.route.fragment.subscribe(fragment => this.token.set(new URLSearchParams(fragment || '').get('token'))); }
  request(): void { if (this.emailForm.invalid) return; this.loading.set(true); this.error.set(''); this.onboarding.requestIdentityPasswordReset(this.emailForm.controls.email.value).subscribe({ next: () => { this.loading.set(false); this.done.set('إذا كان الحساب موجودًا ومؤهلًا، ستصلك رسالة برابط الاستعادة.'); }, error: err => this.fail(err, 'تعذر إرسال الطلب.') }); }
  reset(): void { if (this.passwordForm.invalid) { this.passwordForm.markAllAsTouched(); return; } if (this.passwordForm.controls.password.value !== this.passwordForm.controls.confirmPassword.value) { this.error.set('كلمتا المرور غير متطابقتين.'); return; } const token = this.token(); if (!token) return; this.loading.set(true); this.error.set(''); this.onboarding.resetIdentityPassword(token, this.passwordForm.controls.password.value).subscribe({ next: () => { this.loading.set(false); this.done.set('تم تغيير كلمة المرور وإلغاء الجلسات القديمة.'); }, error: err => this.fail(err, 'الرابط غير صالح أو منتهي.') }); }
  private fail(error: any, fallback: string): void { this.loading.set(false); this.error.set(error?.translatedMessage || error?.error?.message || fallback); }
}
