import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Observable } from 'rxjs';
import { FreelanceOnboardingService } from '../../../../core/freelance/services/freelance-onboarding.service';
import { IdentitySignInResponse, WorkspaceClientJoinPreview, WorkspaceInvitePreview } from '../../../../core/freelance/models/freelance.models';
type Preview = WorkspaceInvitePreview | WorkspaceClientJoinPreview;

@Component({ selector: 'app-identity-join', standalone: true, imports: [CommonModule, ReactiveFormsModule, RouterModule], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<section class="join-flow" dir="rtl"><div class="steps"><b>1</b><span></span><b [class.active]="identity()">2</b><span></span><b [class.active]="done()">3</b></div>
    @if (loading()) { <div class="center"><i class="pi pi-spin pi-spinner"></i><p>جارٍ التحقق من الرابط...</p></div> } @else if (!preview()) { <div class="center"><i class="pi pi-link broken"></i><h2>الرابط غير صالح أو منتهي</h2></div> } @else {
      <header><span class="workspace-logo"><i class="pi" [class.pi-users]="mode() === 'invite'" [class.pi-user-plus]="mode() === 'client'"></i></span><p class="eyebrow">{{ mode() === 'invite' ? 'دعوة فريق' : 'انضمام عميل' }}</p><h2>{{ workspaceName() }}</h2><p>{{ mode() === 'invite' ? 'ستدخل بالدور المحدد في الدعوة: ' + inviteRole() : 'أثبت هويتك لإرسال طلب الانضمام إلى هذه المساحة.' }}</p></header>
      @if (!identity()) { <form [formGroup]="form" (ngSubmit)="signIn()"><label>البريد الإلكتروني<input type="email" formControlName="email" autocomplete="email" dir="ltr"></label><label>كلمة المرور<input type="password" formControlName="password" autocomplete="current-password" dir="ltr"></label><button class="primary" [disabled]="form.invalid || busy()">{{ busy() ? 'جارٍ التحقق...' : 'متابعة' }}</button></form><p class="helper">ليس لديك حساب؟ <a routerLink="/identity/register">أنشئ حسابًا بنفس بريد الدعوة</a></p> } @else if (!done()) { <button class="primary" (click)="complete()" [disabled]="busy()">{{ busy() ? 'جارٍ التنفيذ...' : (mode() === 'invite' ? 'قبول الدعوة' : 'إرسال طلب الانضمام') }}</button><button class="secondary" type="button" routerLink="/identity/login">هذه الدعوة ليست لي</button> } @else { <div class="success"><i class="pi pi-check-circle"></i><h2>تمت العملية بنجاح</h2><a routerLink="/identity/login">العودة إلى الدخول الموحد</a></div> } @if (error()) { <p class="error" role="alert">{{ error() }}</p> }
    }</section>`,
  styles: [`.join-flow{width:100%}.steps{display:flex;align-items:center;justify-content:center;margin-bottom:1.5rem}.steps b{display:grid;place-items:center;width:26px;height:26px;border-radius:50%;background:var(--bg-secondary);color:var(--text-muted)}.steps b:first-child,.steps b.active{background:#2563eb;color:#fff}.steps span{width:55px;height:2px;background:var(--border-color)}header,.center,.success{text-align:center}.workspace-logo{display:grid;place-items:center;width:52px;height:52px;margin:0 auto .7rem;border-radius:16px;background:#eff6ff;color:#2563eb;font-size:1.3rem}.eyebrow{margin:0;color:#2563eb;font-size:.75rem;font-weight:900}h2{margin:.3rem 0;color:var(--text-primary)}header p,.helper{color:var(--text-secondary)}form{display:grid;gap:.55rem}label{font-weight:800;font-size:.86rem}input{min-height:48px;padding:.7rem;border:1px solid var(--border-color);border-radius:10px;background:var(--bg-primary);color:var(--text-primary);font:inherit}.primary,.secondary{width:100%;min-height:48px;margin-top:.8rem;border-radius:10px;font:inherit;font-weight:800;cursor:pointer}.primary{border:0;background:#2563eb;color:#fff}.secondary{border:1px solid var(--border-color);background:transparent;color:var(--text-secondary)}button:disabled{opacity:.6}.helper{text-align:center;font-size:.82rem}.helper a,.success a{color:#2563eb}.error{padding:.7rem;border-radius:8px;background:#fef2f2;color:#b91c1c}.success i{font-size:2.5rem;color:#16a34a}.broken{font-size:2rem;color:#dc2626}`],
})
export class IdentityJoinComponent {
  private readonly route = inject(ActivatedRoute); private readonly onboarding = inject(FreelanceOnboardingService); private readonly fb = inject(FormBuilder);
  readonly mode = signal<'invite'|'client'>((this.route.snapshot.data['mode'] as 'invite'|'client') || 'invite'); readonly preview = signal<Preview|null>(null); readonly token = signal<string|null>(null); readonly loading = signal(true); readonly identity = signal<IdentitySignInResponse|null>(null); readonly busy = signal(false); readonly done = signal(false); readonly error = signal('');
  readonly form = this.fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]], password: ['', Validators.required] });
  constructor() { this.route.fragment.subscribe(fragment => { const token = new URLSearchParams(fragment || '').get(this.mode() === 'invite' ? 'token' : 'code'); this.token.set(token); const request: Observable<Preview> = this.mode() === 'invite' ? this.onboarding.previewWorkspaceInvite(token || '') : this.onboarding.previewClientJoin(token || ''); request.subscribe({ next: value => { this.preview.set(value); this.loading.set(false); }, error: () => this.loading.set(false) }); }); }
  workspaceName(): string { return this.preview()?.workspaceName || ''; } inviteRole(): string { return String((this.preview() as WorkspaceInvitePreview | null)?.role ?? 'عضو'); }
  signIn(): void { if (this.form.invalid) return; const value = this.form.getRawValue(); this.busy.set(true); this.error.set(''); this.onboarding.identityLogin(value.email, value.password).subscribe({ next: value => { this.identity.set(value); this.busy.set(false); }, error: err => { this.fail(err, 'تعذر تسجيل الدخول.'); } }); }
  complete(): void { const token = this.token(), identity = this.identity(); if (!token || !identity) return; this.busy.set(true); this.error.set(''); if (this.mode() === 'client') { this.onboarding.joinWorkspaceAsClient(token, identity.workspaceSelectionToken).subscribe({ next: () => this.success(), error: (err: any) => this.fail(err, 'تعذر إكمال العملية. تحقق من حالة العضوية.') }); } else { this.onboarding.acceptWorkspaceInvite(token, identity.workspaceSelectionToken).subscribe({ next: () => this.success(), error: (err: any) => this.fail(err, 'تعذر إكمال العملية. تحقق من حالة الدعوة.') }); } }
  private success(): void { this.done.set(true); this.busy.set(false); }
  private fail(error: any, fallback: string): void { this.error.set(error?.translatedMessage || error?.error?.message || fallback); this.busy.set(false); }
}
